---

db_hostname: "{{ hostvars[groups['db_server'][0]]['inventory_hostname'] }}"
scm_hostname: "{{ hostvars[groups['scm_server'][0]]['inventory_hostname'] }}"

cluster_display_name: cluster_1

cdh_services:

  - type: hbase

  - type: hdfs
    dfs_data_dir_list: /dfs/dn
    fs_checkpoint_dir_list: /dfs/snn
    dfs_name_dir_list: /dfs/nn
    dfs_journalnode_edits_dir: /dfs/jn

  - type: hive

  - type: hue

  - type: impala
    scratch_dirs: /tmp/impala

  - type: oozie

  - type: sentry

  - type: spark

  - type: yarn
    yarn_nodemanager_local_dirs: /tmp/nm
    yarn_nodemanager_log_dirs: /var/log/nm

  - type: zookeeper

users:
  - name: datagang
    key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDC6NNkkzmLUMQn1fYz0sAUn3rJ3RPdHRyr2JwXO3NVMjB3ezN4t4wGHEgTuScMOSttUnJ9xNt11F8dG+/hAKQyDF7XPFELE4ZExk+JzTAg4/BZiTKjaIERiStE47X5/fbsm4GwzGL5MNDJM7Yj6F7GeW7+mbldHUnnjoWKqbiUY2tsParbDoPyx8Hpmca182RvEcZ+a4aLsDDl7lkc8mqsEnr/iypRLGuaMiQ11jiaZ7n5A44IzSukj3rC26Q2LEu5+/8RrzbpjGjNOp76DIfEDk6itbw9IavEXN432C+cdaqOVmTgd7NOXMnqPbUkRLXoZV95S41/zbjbYN59wIIni4/AFwRpnPoxuFjYusDZqltMx4vgoBVPyG3ff7abO4CywlGp5jcGjWoizUOL3l0t/d8c5zDln2z0nbSkbCKJ1NWVXqpybytc3tYUNwc2k5mIstcPAH1piMXQpNn3gpq5Q9UW7qYS2ZShoVqsKr1QTVOTwFepSPDm6uUiSjlspT8= theoh@DESKTOP-BG29GEL
    edge: edge1
  - name: groupe2
    key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0y1MstO2Aw4ZpGhwLadP7aP9D9PPYzEVjmdgoUv5uAmZr98LV0aNFhC7Bbalmf1RsMk8aQ1mWDlY3XaPzVQrIfXm2GLmmATV17cooVOHVHndXkRfyYpGJ5qWHfczoJPoJcsYaF0MMTIbdUJScUw/whS1khblryi8pHeiH4hbzawqEkLc9L1pqRsYk1fgyqRgyAz2MnaG0yva4700gWg62ffEg+gjkckemjWMwigikRv0wrl8us6STye9UzuDOBIXSeEwgV4JMKvc7CV2I7pBm0I20MduIv8eXZMDourcR2oPZa7oiIvVpXfhV5LSiwxJ8ydFTKzF115tiNFldJfDr victor@debian
    edge: edge2
  - name: talenthunter
    key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmvaL3uE1zJCv5VrmtnAtYE1IvR95Vk2xWtBwMD9gKoFH3AbmOLUg3+fgtZJ3MPs/qKAT9H1UWwUjJ7s1Ap9xabqZ5O6szksESRh4l3SP6VphKQDhor3wM208akCHKZwuverDonUaUXLxEaruQliN5DxWfA3zfDEf7EQYgRcr0KjJ9RivI5BKavTET9QBdkh7P1AQ9J3LPGcmEspcang6DZX19Gfh4aT1Hx3GfgeMVu1jzRkS7jN/sP3b/ZXEqer06H/t2QkAKiuNNLgKD6aYPhrgecIwHjnGzVVt1iLManRXGbhxcNsElbiTpP//CKntqYz2o78/GkW+raIUfvwL9 merzouk@merzouk-HP-Pavilion-Notebook
    edge: edge3
  - name: gpe4
    key: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAjDqlwOYZbME+vCsEfTYeN/lucTigfLDwacQeDXkaCGfDS3ZtUvwI8sMqsxcPlb6dngU14SWUka5IO1VIQW78ATuESPKvDPu+a4tounxBSJMSumWSgBwVGu2HmykGkJCielKhiNPm30vdYvoaB8DEdFtiTZp9V9CDncRT+ldLzZ9bVf8CXax2OFfq1otSKxRS9w6qGrK8efaTdcooXiQ/J6HFdxpcEo3bAmhtxRisHhhtekiBeadaHW9zg6xaQevyQ5FOw4JkMQQ9G7LnoAy5YBrmetzxhSRTMBYQ6roQ8MBfvpOlrwsGnt1jk4h6k6CO2sdGJS+1QweCp8XXxaYOGw==
    edge: edge4
  - name: groupe5
    key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDKs/pIXQwnuMf9kFwks5oBimi0Xn6uhl3KE8emknFo579LI0WMm6E7sm3Ty/naQ7op25pYHEjyXBMhCDKMSfRG6jIW4QzLwkN6TwF51A99AcdOHs8J7WFHR9cjH28vvon87uRp2bwhHBtVJKfm8GbDnTjX32Csj6lTWsJlvm1TPDcV9TDbwJms5BDFm8ZMDEaSGn4X0gMDtO6PmNFrV7ss7bjDZZ4WUi7cVZEK3145s5kc2KcT87DpoAArD59ZH0zsHow/uXyAliYMtkDWPrIdB3BZLqlNIi1N4JNbpYbohfsBjjU9WG1JmXRNJ1kj+nBhqBhloKPr+aXlKwrxSDel kamel@DESKTOP-8MV64OT
    edge: edge5
  - name: groupe6
    key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvEaEmxY4DeDAvP/exWeOBaqcGe1SBSVbziJOKkcbjJrstMr+vbs3X75izm9u0Tgw+3kjtv1a7oDmAyjuIBKjcKME6pZA6crM8ZiYtYYWt+9GZjY18x+bqPTUrJSwdLruyit2EysLDprjZsWvcUnbuUj36CNnGyuIybLEMBo9idMAFiHgXI8J4AoXSkp6ZC3Uj5m5Y35VmZxlU0HJDU39oEYnYtnU/ncHWVbW/hedAdzbqW+lZnZXXlrEDuJD7yeszNwfYrqwgMtXzUrU2rtHpfeB6eneJL8HNAZJuCbeYqVyLNcRcu9CYOn9FxNQvkpBYbc9SF/ZqwDgW/Z8VDlw7 lamien@OMEN-ax231nf
    edge: edge6
  - name: groupe7
    key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtSffqzM0FhDaooJECJLTf6SSUyAhAC80/aCKyoun/acQ1sGVJRypooHbjFlH+lHs4O5tr+Jy0rUvOuEhP21IV4C/2M1zMDesxTr1YpwkK4cdzc56NUxMd7wORoNJ/ju4yiagDuwozdDR1eHnJ3Wve42Lj3awrfwdTJgCtLUXJ+paMhapB9I99aSRGzeLGkIcNKMFAtw1I5G44/oBdYLES4fYDkXLIfbNRDoM4zepOGyA/QNFYn3oSRDWYfnmEG1wxWrRBnfdVQ1ePep/nVJaJw3zqbDOQlKEKft2S8hgS6TqhAD1FLpWNrtIjlQDyRf2kI/25eT3Zh//mxFs1BDtF florian@UB18-VIN
    edge: edge7