---
- name: ensure libselinux-python is installed
  yum:
    name: libselinux-python
    state: installed
    update_cache: yes

- name: disable se-linux
  selinux:
    state: disabled
  register: disable_selinux

- name: Unconditionally reboot the machine with all defaults
  reboot:
    msg: "the sky is falling"
  when: disable_selinux.changed

- name: set hostname
  hostname:
    name: "{{ inventory_hostname | regex_replace('\\.pub\\.cloud\\.scaleway\\.com$', '') }}"

- name: set /etc/hosts
  copy:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: u=rx,g=rx,o=rwx