---
- name: ensure libselinux-python is installed
  yum:
    name: libselinux-python
    state: installed
    update_cache: yes

- name: disable se-linux
  selinux:
    state: disabled
  register: disable_selinux

- name: ensure sudo is installed
  yum:
    name: sudo
    state: installed
    update_cache: yes

- name: Make sure we have a 'student' group
  group:
    name: student
    state: present

- name: Allow 'student' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%student'
    line: '%student ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add noname users to student group
  user: name=noname groups=student append=yes state=present createhome=yes

- name: Add bessa users to student group
  user: name=bessa groups=student append=yes state=present createhome=yes

- name: Add paffme users to student group
  user: name=paffme groups=student append=yes state=present createhome=yes

- name: Add les_trois_petits_nico users to student group
  user: name=les_trois_petits_nico groups=student append=yes state=present createhome=yes

- name: Add vivhaldoop users to student group
  user: name=vivhaldoop groups=student append=yes state=present createhome=yes

- name: Add hapoop users to student group
  user: name=hapoop groups=student append=yes state=present createhome=yes


- name: Unconditionally reboot the machine with all defaults
  reboot:
    msg: "the sky is falling"
  when: disable_selinux.changed

- name: set hostname
  hostname:
    name: "{{ inventory_hostname | regex_replace('\\.pub\\.cloud\\.scaleway\\.com$', '') }}"

- name: set /etc/hosts
  copy:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: u=rx,g=rx,o=rwx
