---
- name: "create user"
  user:
    name: "{{ item }}"
    group: student
  loop: "{{ iabd2 }}"

  #  - name: Set up multiple authorized keys
  #authorized_key:
  # user: deploy
  # state: present
  # key: "keys/{{ item }}.pub"
  # loop: "{{ iabd2 }}"

