- name: ensure sudo is installed
  yum:
    name: sudo
    state: installed
    update_cache: yes

- name: Set up authorized keys for the user
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
  loop: "{{ users }}"
  when: item.edge == inventory_hostname
