---
- name: install python3
  yum:
    name: python3
    state: installed
    update_cache: yes

- name: upgrade pip
  ansible.builtin.shell: pip3 install --upgrade pip

- name: install rust
  ansible.builtin.shell: pip3 install setuptools_rust

- name: install wheel
  ansible.builtin.shell: pip3 install wheel

- name: install airflow
  ansible.builtin.shell: pip3 install "apache-airflow==2.2.2" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.2.2/constraints-3.6.txt"

- name: upgrade sqlite
  ansible.builtin.shell: |
    cd /tmp
    https://www.sqlite.org/2020/sqlite-autoconf-3330000.tar.gz --output sqlite.tar.gz
    tar -zxvf sqlite.tar.gz
    cd sqlite-autoconf-3330000
    ./configure --prefix=/usr/local
    make && make install
    mv sqlite3 sqlite3.7.11
    ln -s /usr/local/bin/sqlite3 /usr/bin/sqlite3
    echo "/usr/local/lib" > /etc/ld.so.conf.d/sqlite3.conf
    ldconfig
    sqlite3 -version

- name: run airflow
  ansible.builtin.shell: airflow standalone
